### ISSUE TITLE
Can I replace wideresnetwithABC with another model?

### ISSUE THREAD

**Issue by kkellyk** [LeeHyuck/ABCtorch#4]
Hi, thanks for this great work!

Find out that your model is using `wideresnetwithABC.py`
Does it contain the ABC of your paper?
Can you tell me which side is the ABC part in` wideresnetwithABC.py`

I want to add ABC to my model.
Is there anything in particular that needs attention?

Thank you for reading
Kelly

**Comment by LeeHyuck** [comment]
Thank you for your interest.
Of course, you can replace wideresnet with another network.
We used wideresnet only because other baseline CISSL (class imbalanced semi supervised learning) algorithms used wideresnet as deep CNN.

classify2 function in the wideresnetwithABC.py works as an ABC.

More details can be found in the paper and code.
